services:
  backend:
    build: ./backend
    command: python -m uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./backend:/code
    ports:
      - "3341:8000"
  frontend:
    build: ./frontend
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
